
let transfers=[],routes=[],clubs=[],meta={};const $=s=>document.querySelector(s);const money=n=>n?new Intl.NumberFormat('en-GB',{style:'currency',currency:'EUR',notation:'compact',maximumFractionDigits:1}).format(n):'—';
Promise.all(['transfers','routes','clubs','meta'].map(x=>fetch(`data/${x}.json`).then(r=>r.json()))).then(([t,r,c,m])=>{transfers=t;routes=r;clubs=c;meta=m;init()});
function init(){document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')});
$('#summary').innerHTML=`<div class=card><b>${meta.transfer_count.toLocaleString()}</b><span>canonical movements</span></div><div class=card><b>${meta.bidirectional_route_count.toLocaleString()}</b><span>bidirectional routes</span></div><div class=card><b>5</b><span>major leagues</span></div><div class=card><b>11</b><span>seasons</span></div>`;
const opts=['<option value="">Select club</option>',...clubs.map(x=>`<option>${esc(x)}</option>`)].join('');$('#clubA').innerHTML=opts;$('#clubB').innerHTML=opts;$('#showRoute').onclick=()=>showPair($('#clubA').value,$('#clubB').value);
meta.leagues.forEach(l=>{$('#routeLeague').insertAdjacentHTML('beforeend',`<option>${l}</option>`)});$('#routeSearch').oninput=renderRoutes;$('#routeLeague').onchange=renderRoutes;renderRoutes();renderLeagues();$('#metaText').textContent=`Dataset: ${meta.seasons}; ${meta.transfer_count.toLocaleString()} canonical movements.`;
const q=new URLSearchParams(location.search);if(q.get('a')&&q.get('b')){$('#clubA').value=q.get('a');$('#clubB').value=q.get('b');showPair(q.get('a'),q.get('b'))}}
function renderRoutes(){let q=$('#routeSearch').value.toLowerCase(),l=$('#routeLeague').value;let rr=routes.filter(r=>(!q||(r.club_a+' '+r.club_b).toLowerCase().includes(q))&&(!l||r.leagues.includes(l)));$('#routeRows').innerHTML=rr.slice(0,500).map(r=>`<tr class=clickable onclick='showPair(${js(r.club_a)},${js(r.club_b)})'><td>${r.rank}</td><td>${esc(r.club_a)} ↔ ${esc(r.club_b)}</td><td><b>${r.total}</b></td><td>${r.a_to_b}</td><td>${r.b_to_a}</td><td>${r.unique_players}</td><td>${r.loans}</td><td>${r.balance_pct}%</td></tr>`).join('')}
function showPair(a,b){if(!a||!b||a===b)return;let rr=transfers.filter(x=>(x.from_club===a&&x.to_club===b)||(x.from_club===b&&x.to_club===a));let route=routes.find(r=>r.club_a===a&&r.club_b===b||r.club_a===b&&r.club_b===a);history.replaceState(null,'',`?a=${encodeURIComponent(a)}&b=${encodeURIComponent(b)}`);$('#routeView').innerHTML=`<h2 class=route-title>${esc(a)} ↔ ${esc(b)}</h2>${route?`<div class=cards><div class=card><b>${route.total}</b><span>movements</span></div><div class=card><b>${route.unique_players}</b><span>unique players</span></div><div class=card><b>${route.loans}</b><span>loans</span></div><div class=card><b>${route.balance_pct}%</b><span>directional balance</span></div></div>`:''}<div class=tablebox><table><thead><tr><th>Season</th><th>Window</th><th>Player</th><th>Direction</th><th>Type</th><th>Fee</th><th>Confidence</th></tr></thead><tbody>${rr.map(x=>`<tr><td>${x.season_label}</td><td>${x.window}</td><td><b>${esc(x.player_name)}</b></td><td>${esc(x.from_club)} → ${esc(x.to_club)}</td><td><span class="pill ${x.is_loan?'loan':''}">${x.is_loan?'Loan':esc(x.transfer_type)}</span></td><td class=money>${money(x.fee_eur)}</td><td>${esc(x.fee_status)}</td></tr>`).join('')}</tbody></table></div>`;$('#routeView').scrollIntoView({behavior:'smooth'})}
function renderLeagues(){$('#leagueLists').innerHTML=meta.leagues.map(l=>`<h3>${l}</h3><div class=tablebox><table><thead><tr><th>Rank</th><th>Route</th><th>Total</th><th>Both directions</th><th>Players</th><th>Loans</th></tr></thead><tbody>${routes.filter(r=>r.leagues.includes(l)).slice(0,10).map((r,i)=>`<tr class=clickable onclick="document.querySelector('[data-tab=routes]').click();showPair(${js(r.club_a)},${js(r.club_b)})"><td>${i+1}</td><td>${esc(r.club_a)} ↔ ${esc(r.club_b)}</td><td>${r.total}</td><td>${r.a_to_b} / ${r.b_to_a}</td><td>${r.unique_players}</td><td>${r.loans}</td></tr>`).join('')}</tbody></table></div>`).join('')}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function js(s){return JSON.stringify(s).replace(/</g,'\\u003c')}
